### ISSUE TITLE
create alloc free version of transform

### ISSUE THREAD

**Issue by jackielii** [pebbe/go-proj-4#11]
```func transform(srcpj, dstpj *Proj, x, y, z []float64) ([]float64, []float64, []float64, error)``` 

always allocates the result `[]float64`. this can be improved with 

```func transform(srcpj, dstpj *Proj, x, y, z []float64, u, v, w []float64) (error)```

**Comment by pebbe** [comment]
Then I'd have to allocated the result in the calling functions. What would this accomplish?

**Comment by jackielii** [comment]
@pebbe if I allocate a buffer and reuse it every time I call transform, would that save some GC time?

something like this:

```go
var x, y []float64 = ... // large enough buffer for the following loop
for _, line := range lines {
  x0 := getxfromline(line)
  y0 := getyfromline(line)
  x = x[:len(x0)]
  y = y[:len(y0)]
  err := proj.Transform2lst(srcCRS, targetCRS, x0, y0, x, y)
  ...
}
```

my transform is in a loop that I don't want the allocate new buffer for every iteration. Am I thinking too much or does the compiler optimise this?

**Comment by pebbe** [comment]
That would be a backward incompatible change.

**Comment by jackielii** [comment]
understood, I think for my use case, I should roll my own solution.
