### ISSUE TITLE
breakage for proj.4 4.8.0 -> 4.9.1?

### ISSUE THREAD

**Issue by peribothron** [pebbe/go-proj-4#5]
go-proj-4 [e.g., tests] work fine for proj.4 4.8.0 [circa march 2012]  but fail for 4.9.1 [circa march 2015]. is go-proj-4 tracking proj releases? if yes, then this may be an unrelated os/userland proj packaging issue instead. if no, then see below.

workaround unknown.
notes follow:
os: archlinux.
using packaged proj. (4.8.0 works fine). have not tried installing proj 4.9.1 directly from source.

$ go get -u github.com/pebbe/go-proj-4/proj
$ cd github.com/pebbe/go-proj-4/proj
$ proj
Rel. 4.9.1, 04 March 2015
usage: proj [ -beEfiIlormsStTvVwW [args] ] [ +opts[=arg] ] [ files ]
$ go test
--- FAIL: TestMercToLatlong (0.00s)
    proj_test.go:18: major axis or radius = 0 or not given
    proj_test.go:23: projection is closed
--- FAIL: TestInvalidErrorProblem (0.00s)
    proj_test.go:43: major axis or radius = 0 or not given
FAIL
exit status 1
FAIL    github.com/pebbe/go-proj-4/proj 0.037s

# ls -l proj*
-rw-r--r-- 1 root root 3156060 Dec 28  2013 proj-4.8.0-3-armv7h.pkg.tar.xz
-rw-r--r-- 1 root root 3222600 Mar 13 10:25 proj-4.9.1-1-armv7h.pkg.tar.xz

[downgrading package proj (4.9.1-1 => 4.8.0-3)]
$ proj
Rel. 4.8.0, 6 March 2012
usage: proj [ -beEfiIlormsStTvVwW [args] ] [ +opts[=arg] ] [ files ]
$ go test
PASS
ok      github.com/pebbe/go-proj-4/proj 0.032s
--------------------------------------------------
reviewing https://trac.osgeo.org/proj/
https://svn.osgeo.org/metacrs/proj/trunk/proj/NEWS
does not mention any 4.8 -> 4.9 incompatible changes?

perhaps go-proj could expose [or at least test] pj_get_release() to clarify tracking / compatibility / issues with upstream proj-4.
https://svn.osgeo.org/metacrs/proj/trunk/proj/src/pj_release.c:
char const pj_release[]="Rel. 4.9.1, 04 March 2015";

**Comment by pebbe** [comment]
Fixed
