### ISSUE TITLE
Concurrent access causes panic

### ISSUE THREAD

**Issue by rnix** [pebbe/go-proj-4#6]
When running `Transform` in goroutines, it will intermittently panic:

    e = C.transform(srcpj.pj, dstpj.pj, C.long(ln), &x1[0], &y1[0], nil)

Here's the panic:

	fatal error: unexpected signal during runtime execution

	goroutine 12 [syscall, locked to thread]:
	runtime.cgocall_errno(0x40047c0, 0xc2080e9788, 0xc200000000)
		/usr/local/go/src/runtime/cgocall.go:130 +0xf5 fp=0xc2080e9768 sp=0xc2080e9740
	github.com/pebbe/go-proj-4/proj._Cfunc_transform(0x9300100, 0x9300540, 0x1, 0xc2081c0650, 0xc2081c0658, 0x0, 0x0)
		github.com/pebbe/go-proj-4/proj/_obj/_cgo_gotypes.go:79 +0x44 fp=0xc2080e9788 sp=0xc2080e9768
	github.com/pebbe/go-proj-4/proj.transform(0xc20802c970, 0xc20802c990, 0xc2080e99a8, 0x1, 0x1, 0xc2080e99a0, 0x1, 0x1, 0x0, 0x0, ...)
		/Users/Shared/Development/git.urban4m.com/projects/AP/app-tiler/src/github.com/pebbe/go-proj-4/proj/proj.go:114 +0xac1 fp=0xc2080e98e8 sp=0xc2080e9788
	github.com/pebbe/go-proj-4/proj.Transform2(0xc20802c970, 0xc20802c990, 0xbff4fc1f999beca7, 0x3fe74af9b8a9018a, 0x2, 0x2, 0x0, 0x0)
		/Users/Shared/Development/git.urban4m.com/projects/AP/app-tiler/src/github.com/pebbe/go-proj-4/proj/proj.go:138 +0x157 fp=0xc2080e9a28 sp=0xc2080e98e8

**Comment by pebbe** [comment]
Don't do concurrent access.

**Comment by rnix** [comment]
Yikes. That's a painful answer for a Go library. Do you happen know why this doesn't work?

**Comment by pebbe** [comment]
It isn't a pure Go library. It's just a wrapper around a C library that happens to be not thread-safe. If you want to use it in multiple goroutines you need to protect it with a mutex.

**Comment by rnix** [comment]
Proj4's (and GDAL's) limitations seem pretty random and unexpected, presumably due to the overuse of globals and mutability. I'd sure love to have the time to rewrite them in pure Go.
Anyway, yea, I worked around it with a mutex. Not a big deal but it's just in some pretty concurrency-heavy code and a mutex feels gross :)
