### ISSUE TITLE
Does not find proj-4 header and library with homebrew on OS X

### ISSUE THREAD

**Issue by jum** [pebbe/go-proj-4#9]
I am using homebrew on my mac to maintain a few packages like proj-4 which installs all headers and libraries in /usr/local/{include,lib}. If I change the cgo directive to use pkg-config it will pick the location of the header files and libraries properly.

> diff --git a/proj/proj.go b/proj/proj.go
index e451626..917383c 100644
--- a/proj/proj.go
+++ b/proj/proj.go
@@ -26,7 +26,7 @@ Example usage:
 package proj

 /*
-#cgo LDFLAGS: -lproj
+#cgo pkg-config: proj
 #include "proj.h"
 */
 import "C"

**Comment by pebbe** [comment]
This doesn't work on linux, because proj-4 doesn't use pkg-config on linux.

I made a change that hopefully fixes this for mac, without breaking on linux. Could you test this please?

**Comment by jum** [comment]
This works nicely now on OS X, thanks.
--
Jens-Uwe Mager  <pgp-mailto:D5D75498>
